TARGET = libConsole.a
INCLUDES = ../../include ../../../arch/arch/include ../../include/console ../../../arch/common/include
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
