TARGET = libConsole.a
INCLUDES = ../../include/util ../../include ../../../arch/arch/include ../../include/console ../../include/kernel ../../../arch/common/include ../../include/ipc ../../include/drivers 
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
