TARGET = libArchSpecific.a
INCLUDES = ../include ../include/xen-public ../include/xen-public/io ../../../common/include/mm/ ../../../common/include/kernel/ ../../common/include ../../../common/include/console ../../../common/include/drivers ../../../common/include/util ../../../common/include/ipc/ ../../../common/include
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
