TARGET = libDeviceFS.a
MAKEFLAGS :=
INCLUDES = ../../../include ../../../../arch/arch/include ../../../include/mm ../../../../arch/common/include ../../../include/fs ../../../include/console ../../../include/kernel
SUBPROJECTS = 
PROJECT_ROOT = ../../../..
include ../../../../make-support/common.mk
MAKEFLAGS :=
