TARGET = libKernel.a
INCLUDES = ../../include ../../../arch/arch/include ../../../arch/common/include ../../include/kernel
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
