TARGET = libKernel.a
INCLUDES = ../../include ../../../arch/arch/include ../../../arch/common/include ../../include/kernel ../../include/drivers ../../include/ipc ../../include/util
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
