TARGET = libUtil.a
INCLUDES = ../../include/util ../../include ../../../arch/arch/include ../../include/mm ../../../arch/common/include
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
