
#
# CVS Log Info for $RCSfile: Makefile,v $
#
# $Id: Makefile,v 1.1 2005/05/10 16:33:06 davrieb Exp $
# $Log$
#

TARGET = libFS.a
MAKEFLAGS :=
INCLUDES = ../../include ../../../arch/arch/include ../../include/mm ../../../arch/common/include ../../include/fs
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
MAKEFLAGS :=
