#pragma once

constexpr const char* errors[32] = {
  "#DE: Divide by Zero",
  "#DB: Debug",
  "NMI: Non-maskable Interrupt",
  "#BP: Breakpoint",
  "#OF: Overflow (INTO Instruction)",
  "#BR: Bound Range Exceeded",
  "#OP: Invalid OP Code",
  "#NM: FPU Not Avaiable or Ready",
  "#DF: Double Fault",
  "#MF: FPU Segment Overrun",
  "#TS: Invalid Task State Segment (TSS)",
  "#NP: Segment Not Present (WTF ?)",
  "#SS: Stack Segment Fault",
  "#GF: General Protection Fault",
  "#PF: Page Fault",
  "reserved",
  "#MF: Floting Point Error",
  "#AC: Alignment Error (Unaligned Memory Reference)",
  "#MC: Machine Check Error",
  "#XF: SIMD Floting Point Error",
  "#VE: Virtualization Exception",
  "#CP: Control Protection Exception",
  "reserved",
  "reserved",
  "reserved",
  "reserved",
  "reserved",
  "reserved",
  "#HV: Hypervisor Injection Exception",
  "#VC: VMM Communication Exception",
  "#SX: Security Exception",
  "reserved"
};
