TARGET := mtools
INCLUDES := .
SUBPROJECTS := 
SHARED_LIBS := 
PROJECT_ROOT := ../../
SWEB_COMPILE_USERSPACE := 4223
CCFLAGS :=  -DHAVE_CONFIG_H -DSYSCONFDIR=\"/usr/local/etc\" -DCPU_x86_64 -DVENDOR_unknown -DOS_linux_gnu -fno-strict-aliasing
include ../../make-support/common.mk
