TARGET = libArchSpecific.a
INCLUDES = ../include ../../../common/include/mm/ ../../common/include ../../../common/include/console
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
