TARGET = libArchSpecific.a
INCLUDES = ../include ../../../common/include/mm/ ../../../common/include/kernel/ ../../common/include ../../../common/include/console ../../../common/include/ipc ../../../common/include/drivers ../../../common/include/util  ../../../common/include
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
