TARGET = libRamFS.a
MAKEFLAGS :=
INCLUDES = ../../../include ../../../../arch/arch/include ../../../include/mm ../../../../arch/common/include ../../../include/fs
SUBPROJECTS =
PROJECT_ROOT = ../../../..
include ../../../../make-support/common.mk
MAKEFLAGS :=
