
#
# CVS Log Info for $RCSfile: Makefile,v $
#
# $Id: Makefile,v 1.1 2005/07/07 12:31:48 davrieb Exp $
# $Log: Makefile,v $
# Revision 1.2  2005/06/01 09:20:36  davrieb
# add all changes to fs
#
# Revision 1.1  2005/05/10 16:33:06  davrieb
# add Makefile for fs
#
#

TARGET = libRamFS.a
MAKEFLAGS :=
INCLUDES = ../../../include ../../../../arch/arch/include ../../../include/mm ../../../../arch/common/include ../../../include/fs
SUBPROJECTS = 
PROJECT_ROOT = ../../../..
include ../../../../make-support/common.mk
MAKEFLAGS :=
