
#
# CVS Log Info for $RCSfile: Makefile,v $
#
# $Id: Makefile,v 1.1 2005/05/13 06:21:22 btittelbach Exp $
# $Log: Makefile,v $
# Revision 1.1  2005/05/10 16:33:06  davrieb
# add Makefile for fs
#
#

TARGET = libDrivers.a
MAKEFLAGS :=
INCLUDES = ../../include ../../../arch/arch/include ../../include/mm ../../../arch/common/include ../../include/drivers ../../include/console/
SUBPROJECTS = 
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
MAKEFLAGS :=
