TARGET = libDrivers.a
MAKEFLAGS :=
INCLUDES = ../../include ../../../arch/arch/include ../../include/mm ../../../arch/common/include ../../include/drivers ../../include/console/
SUBPROJECTS =
PROJECT_ROOT = ../../..
include ../../../make-support/common.mk
MAKEFLAGS :=
